# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

env:
    global:
        - SETUP_CMD='test'
        - TEST_CMD='py.test test_env.py'
        - PYTHON_VERSION=3.6
        - SETUP_CONDA=true

jobs:
    include:
        # pytest dev version
        - arch: arm64
          os: linux
        - os: linux
before_install:
    - if [[ $TRAVIS_OS_NAME == windows ]]; then
        cp -R . ../ci-helpers-temp;
        mv ../ci-helpers-temp ci-helpers;
      else
        ln -s . ci-helpers;
      fi
    - if [[ $SETUP_CONDA == true ]]; then source ci-helpers/travis/setup_conda.sh; fi

script:
   - python --version
   - eval $TEST_CMD

after_success:
   - if [[ $SETUP_CMD == *coverage* ]]; then coveralls; fi
