# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

sudo: false

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - SETUP_CMD='test'
        - TEST_CMD='py.test test_env.py'
        - PYTHON_VERSION=3.5

    matrix:
        - SETUP_CMD='egg_info'
          TEST_CMD='python --version'

        - SETUP_CMD='test'

matrix:
    include:

        # Starting with the dev versions as they take the longest to run
        - os: linux
          env: SETUP_CMD='test' NUMPY_VERSION=1.10 ASTROPY_VERSION=dev

        # For the Numpy dev build, we also specify a conda package that depends
        # on Numpy to make sure that Numpy dev is used (because conda will also
        # install Numpy stable)

        - os: linux
          env: SETUP_CMD='test' NUMPY_VERSION=dev
               CONDA_DEPENDENCIES='scipy'

        - os: linux
          env: SETUP_CMD='build_sphinx' CONDA_DEPENDENCIES='matplotlib<=1.5.0'
               DEBUG=True
               TEST_CMD='python -c "import matplotlib; assert matplotlib.__version__=="\""1.5.0"\"'

        - os: linux
          env: SETUP_CMD='build_sphinx' CONDA_DEPENDENCIES='matplotlib=1.5.0 sphinx'
               MATPLOTLIB_VERSION=1.5.1 DEBUG=True
               TEST_CMD='python -c "import matplotlib; assert matplotlib.__version__=="\""1.5.1"\"'

        - os: linux
          env: SETUP_CMD='build_docs' PYTHON_VERSION=2.7

        - os: linux
          env: MAIN_CMD='pep8'
               TEST_CMD='pep8 --version'

        - os: osx
          env: SETUP_CMD='test' ASTROPY_VERSION=LTS
               CONDA_DEPENDENCIES='requests'

        - os: linux
          env: SETUP_CMD='test' NUMPY_VERSION=1.10 DEBUG=True
               CONDA_DEPENDENCIES='Cython numpy scikit-image'

        - os: linux
          env: SETUP_CMD='test' ASTROPY_VERSION=stable

        - os: linux
          env: SETUP_CMD='test' NUMPY_VERSION=1.9 CONDA_DEPENDENCIES='requests'

        - os: linux
          env: SETUP_CMD='test' NUMPY_VERSION=1.9 ASTROPY_VERSION=1.0
               CONDA_DEPENDENCIES='matplotlib h5py'
               PIP_DEPENDENCIES='astrodendro'

        - os: linux
          env: SETUP_CMD='test' NUMPY_VERSION=stable

        - os: linux
          env: SETUP_CMD='test' ASTROPY_VERSION=LTS

        - os: linux
          env: SETUP_CMD='test --parallel'
               TEST_CMD='py.test -n 4 test_env.py'

        - os: linux
          env: SETUP_CMD='test --open-files'

        - os: linux
          env: SETUP_CMD='test --coverage' PYTHON_VERSION=2.7
               TEST_CMD='coverage run test_env.py'
               CONDA_CHANNELS='astropy-ci-extras astrofrog'
               CONDA_DEPENDENCIES='pyqt5' DEBUG=True
               NUMPY_VERSION=1.10 ASTROPY_VERSION=lts

before_install:
    - ln -s . ci-helpers
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
   - eval $TEST_CMD
   - if [[ $SETUP_CMD == *coverage* ]]; then coveralls; fi
