language: python

python:
    - 2.7
    - 3.5

sudo: false

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - SETUP_CMD='test'
        - TEST_CMD='py.test test_env.py'
    matrix:
        - SETUP_CMD='egg_info'
          TEST_CMD='python --version'

        - SETUP_CMD='test'

matrix:
    include:
        - python: 3.5
          env: SETUP_CMD='build_sphinx'

        - python: 2.7
          env: SETUP_CMD='build_docs'

        - python: 3.5
          env: MAIN_CMD='pep8'
               TEST_CMD='pep8 --version'

        - python: 3.5
          env: SETUP_CMD='test' NUMPY_VERSION=1.10

        - python: 3.5
          env: SETUP_CMD='test' ASTROPY_VERSION=1.0

        - python: 3.5
          env: SETUP_CMD='test' NUMPY_VERSION=1.9 CONDA_DEPENDENCIES='requests'

        - python: 3.5
          env: SETUP_CMD='test' NUMPY_VERSION=1.9 ASTROPY_VERSION=1.0
               CONDA_DEPENDENCIES='matplotlib h5py' PIP_DEPENDENCIES='astrodendro'
        - python: 3.5
          env: SETUP_CMD='test' NUMPY_VERSION=dev

        - python: 3.5
          env: SETUP_CMD='test' NUMPY_VERSION=stable

        - python: 3.5
          env: SETUP_CMD='test' NUMPY_VERSION=1.10 ASTROPY_VERSION=dev

        - python: 2.7
          env: SETUP_CMD='test'
               CONDA_CHANNELS='astropy-ci-extras astrofrog'
               CONDA_DEPENDENCIES='PyQt5'


before_install:
    - ln -s . ci-helpers
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
   - eval $TEST_CMD
