language: python

python:
    - 2.7

sudo: false

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - SETUP_CMD='test'
        - MAIN_CMD='python setup.py'

matrix:
    include:
        - python: 2.7
          env: SETUP_CMD='test'
               TEST_CMD='python --version'
        - python: 3.5
          env: SETUP_CMD='test'
               TEST_CMD='python --version'
        - python: 3.5
          env: SETUP_CMD='egg_info'
               TEST_CMD='python --version'
        - python: 3.5
          env: SETUP_CMD='build_sphinx'
               TEST_CMD='python -c "import sphinx"'
        - python: 3.5
          env: MAIN_CMD='pep8'
               TEST_CMD='pep8 --version'
        - python: 3.5
          env: SETUP_CMD='test' NUMPY_VERSION=1.10 
               TEST_CMD='python -c "import numpy; assert numpy.__version__.startswith(\"1.10\")"'
        - python: 3.5
          env: SETUP_CMD='test' ASTROPY_VERSION=1.0
               TEST_CMD='python -c "import astropy; assert astropy.__version__.startswith(\"1.0\")"'
        - python: 3.5
          env: SETUP_CMD='test' NUMPY_VERSION=1.9 CONDA_DEPENDENCIES='requests'
               TEST_CMD='python -c "import numpy; import requests; assert numpy.__version__.startswith(\"1.9\")"'
        - python: 3.5
          env: SETUP_CMD='test' NUMPY_VERSION=1.9 ASTROPY_VERSION=1.0
               CONDA_DEPENDENCIES='matplotlib h5py' PIP_DEPENDENCIES='astrodendro'
               TEST_CMD='python -c "import astrodendro"'

before_install:
    - ln -s . ci-helpers
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
   - eval $TEST_CMD
