# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

sudo: false

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - SETUP_CMD='test'
        - TEST_CMD='py.test test_env.py'
    matrix:
        - SETUP_CMD='egg_info'
          TEST_CMD='python --version'

        - SETUP_CMD='test'

matrix:
    include:
        - python: 3.5
          env: SETUP_CMD='build_sphinx'

        - python: 2.7
          env: SETUP_CMD='build_docs'

        - python: 3.5
          env: MAIN_CMD='pep8'
               TEST_CMD='pep8 --version'

        - python: 3.5
          env: SETUP_CMD='test' NUMPY_VERSION=1.10

        - python: 3.5
          env: SETUP_CMD='test' ASTROPY_VERSION=1.0

        - python: 3.5
          env: SETUP_CMD='test' NUMPY_VERSION=1.9 CONDA_DEPENDENCIES='requests'

        - python: 3.5
          env: SETUP_CMD='test' NUMPY_VERSION=1.9 ASTROPY_VERSION=1.0
               CONDA_DEPENDENCIES='matplotlib h5py' PIP_DEPENDENCIES='astrodendro'

        # For the Numpy dev build, we also specify a conda package that depends
        # on Numpy to make sure that Numpy dev is used (because conda will also
        # install Numpy stable)
        - python: 3.5
          env: SETUP_CMD='test' NUMPY_VERSION=dev
               CONDA_DEPENDENCIES='scipy'

        - python: 3.5
          env: SETUP_CMD='test' NUMPY_VERSION=stable

        - python: 3.5
          env: SETUP_CMD='test' NUMPY_VERSION=1.10 ASTROPY_VERSION=dev

        - python: 3.5
          env: SETUP_CMD='test' ASTROPY_VERSION=lts

        - python: 3.5
          env: SETUP_CMD='test' ASTROPY_VERSION=LTS

        - python: 3.5
          env: SETUP_CMD='test --parallel'
               TEST_CMD='py.test -n 4 test_env.py'

        - python: 3.5
          env: SETUP_CMD='test --open-files'

        - python: 3.5
          env: SETUP_CMD='test --coverage'
               TEST_CMD='coverage run test_env.py'

        - python: 2.7
          env: SETUP_CMD='test'
               CONDA_CHANNELS='astropy-ci-extras astrofrog'
               CONDA_DEPENDENCIES='PyQt5'

        - python: 3.5
          env: SETUP_CMD='test' DEBUG=True

        - python: 3.5
          env: SETUP_CMD='test' DEBUG=False

        - os: osx
          python: 3.5
          env: SETUP_CMD='test' ASTROPY_VERSION=LTS


before_install:
    - ln -s . ci-helpers
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
   - eval $TEST_CMD
   - if [[ $SETUP_CMD == *coverage* ]]; then coveralls; fi
